version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.0
